### ISSUE TITLE
Don't use px units for padding, margins and such

### ISSUE THREAD

**Issue by joostf** [larsdouweschuitema/minor-meesterproef#19]
https://github.com/larsdouweschuitema/minor-meesterproef/blob/d7832d60947ff92246247b8aee20d552fcd0df3f/src/scss/_filters.scss#L4

https://github.com/larsdouweschuitema/minor-meesterproef/blob/d7832d60947ff92246247b8aee20d552fcd0df3f/src/scss/_rankings.scss#L9

**Comment by larsdouweschuitema** [comment]
Changes all paddings / margins to em's
