### ISSUE TITLE
Improve games view semantics

### ISSUE THREAD

**Issue by joostf** [larsdouweschuitema/minor-meesterproef#22]
Don't use heading elements in form. Consider using fieldsets with legends (a pain to style though) for each game

https://github.com/larsdouweschuitema/minor-meesterproef/blob/d7832d60947ff92246247b8aee20d552fcd0df3f/views/games.ejs#L4

**Comment by larsdouweschuitema** [comment]
I agree. There are no more headings inside forms in the current version. In the future I will use legends for this. Thanks!
