### ISSUE TITLE
Don’t specify `/` in `path.join`

### ISSUE THREAD

**Issue by wooorm** [larsdouweschuitema/minor-meesterproef#35]
`path.join` already adds the proper slashes for you, and the reason to use `.join` is to make stuff work on Windows too, in which case `\` instead of `/` should be used (and `.join` already handles that).

[`server.js#L19`](https://github.com/larsdouweschuitema/minor-meesterproef/blob/c9c80961cf15844f4c486f85b26cdb41cf3d5adc/server.js#L19):

```js
const modelsPath = path.join(__dirname, '/models');
```

**Comment by larsdouweschuitema** [comment]
Thanks, fixed!
