### ISSUE TITLE
Use `fs`, not `file-system`

### ISSUE THREAD

**Issue by wooorm** [larsdouweschuitema/minor-meesterproef#36]
`fs` is the module packaged with Node, `file-system` is a weird module on npm. I’m guessing you wanted to use `fs`?

[`server.js#L4`](https://github.com/larsdouweschuitema/minor-meesterproef/blob/ef61972bedec3a724d782060406bc9f95f60f97b/server.js#L4):

```js
const fs = require('file-system');
```

**Comment by larsdouweschuitema** [comment]
Yeah that's true, but: https://www.npmjs.com/package/fs
Can't find the original. If this is the one, it's quite empty.
