### ISSUE TITLE
Don’t specify `path` in `package.json`

### ISSUE THREAD

**Issue by wooorm** [larsdouweschuitema/minor-meesterproef#37]
`path` is a module packaged with Node, you don’t need to specify it in `package.json` (same with `fs`, related to GH-36).

[`package.json#L28`](https://github.com/larsdouweschuitema/minor-meesterproef/blob/ef61972bedec3a724d782060406bc9f95f60f97b/package.json#L28):

```js
    "mongoose": "^4.10.6",
    "path": "^0.12.7",
    "request": "^2.81.0"
```

**Comment by larsdouweschuitema** [comment]
Thanks. Removed.
