### ISSUE TITLE
Don’t nest CSS selectors too deep

### ISSUE THREAD

**Issue by wooorm** [larsdouweschuitema/minor-meesterproef#41]
In [`rankings`](https://github.com/larsdouweschuitema/minor-meesterproef/blob/ef61972bedec3a724d782060406bc9f95f60f97b/src/scss/_rankings.scss), you’re creating a CSS selector for images that expands to `table tr td img.rating`, you could probably cut that down to `table .rating`.

**Comment by larsdouweschuitema** [comment]
Agree, changed that.
